# SPDX-License-Identifier: GPL-2.0-only
"""Extract ordered, width-preserving tables from the pinned IMX708 reference."""
import argparse
import hashlib
import re
from pathlib import Path

SHA256 = "d83d25e985faacd8029a7dcc98be9c749e060953b292335337b2e43df9a58704"
TABLES = ("mode_common_regs", "mode_4608x2592_regs", "mode_2x2binned_regs")


def generate(source):
    if hashlib.sha256(source).hexdigest() != SHA256:
        raise ValueError("IMX708 reference SHA-256 mismatch; review upstream changes first")
    text = source.decode()
    defines = dict(re.findall(r"^\s*#define\s+(IMX708_\w+)\s+([^\n]+)", text, re.MULTILINE))

    def resolve(value):
        value = value.strip()
        return defines.get(value, value).strip()

    lines = ["// SPDX-License-Identifier: GPL-2.0-only",
             "// Derived from Sony IMX708 driver, Copyright (C) 2022 Raspberry Pi Ltd.",
             "// Generated by generate-registers.py; preserve ordering and widths.",
             "#pragma once", '#include "sensor.hpp"', "namespace imx708 {"]
    for name in TABLES:
        match = re.search(r"static const struct cci_reg_sequence " + name
                          + r"\[\] = \{(.*?)\n\};", text, re.DOTALL)
        if not match:
            raise ValueError(f"Missing table: {name}")
        lines.append(f"inline constexpr Register {name}[] = {{")
        for line in match[1].strip().splitlines():
            entry = re.fullmatch(r"\s*\{(.+?),\s*(.+?)\},\s*", line)
            if not entry:
                raise ValueError(f"Unparsed register: {line}")
            register = re.fullmatch(r"CCI_REG(8|16)\((0x[0-9a-fA-F]+)\)", resolve(entry[1]))
            if not register:
                raise ValueError(f"Unsupported register: {entry[1]}")
            width = int(register[1]) // 8
            address, value = int(register[2], 16), int(resolve(entry[2]), 0)
            if not 0 <= value < 1 << (8 * width):
                raise ValueError("Register value overflow")
            lines.append(f"    {{0x{address:04x}, 0x{value:04x}, {width}}},")
        lines.append("};")
    lines.append("} // namespace imx708\n")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        result = generate(args.source.read_bytes())
    except ValueError as error:
        parser.error(str(error))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(result)


if __name__ == "__main__":
    main()
