# SPDX-License-Identifier: MIT
# Require hardware-accelerated glamor for the Q6A desktop.
Section "Device"
    Identifier "Q6A display"
    Driver "modesetting"
    Option "AccelMethod" "glamor"
EndSection
