# SPDX-License-Identifier: MIT
[Unit]
After=systemd-user-sessions.service plymouth-quit-wait.service
Wants=systemd-user-sessions.service

[Service]
User=weston
Group=weston
PAMName=qcom-xfce-autologin
WorkingDirectory=/home/weston
EnvironmentFile=
Environment=HOME=/home/weston USER=weston LOGNAME=weston LANG=en_US.UTF-8 XDG_SESSION_TYPE=x11 XDG_SESSION_DESKTOP=xfce XDG_CURRENT_DESKTOP=XFCE
ExecStartPre=+/usr/bin/install -d -o weston -g weston -m 0755 /home/weston/.local/share
ExecStartPre=+/usr/bin/chvt 7
ExecStart=
ExecStart=/usr/bin/qcom-xfce-start
TTYPath=/dev/tty7
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=yes
StandardInput=tty
StandardOutput=journal
StandardError=journal
UtmpIdentifier=tty7
UtmpMode=user
RestartSec=3
