# SPDX-License-Identifier: MIT
context.modules = [
    { name = libpipewire-module-pal
      args = {
        node.name = "pal_sink_headset_ll"
        node.description = "Q6A WCD9385 Headphones"
        media.class = "Audio/Sink"
        media.role = "notification"
        jack-name = "Headset Jack"
        headphone-only = true
        stream.props = {
            audio.position = [ FL FR ]
            audio.rate = 48000
            q6a.jack.connected = false
        }
      }
    }
]
