[General]
bitbake_subdir = layers/oe-core/bitbake
init_path = layers/oe-core/oe-init-build-env
core_meta_subdir = layers/oe-core/meta
workspace_path = /home/dsh/Desktop/qcom_sdk/workspace

[SDK]
sdk_targets = qcom-multimedia-proprietary-image
target_basename = qcom-minimal-efi-sd-image

